/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as EntrarRouteImport } from './routes/entrar'
import { Route as CuponsRouteImport } from './routes/cupons'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as AdminLayoutRouteImport } from './routes/_adminLayout'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PedidoIdRouteImport } from './routes/pedido.$id'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminLayoutAdminIndexRouteImport } from './routes/_adminLayout.admin.index'
import { Route as ApiPublicOrdersRouteImport } from './routes/api/public/orders'
import { Route as ApiConsumerOrdersRouteImport } from './routes/api/consumer/orders'
import { Route as ApiConsumerDiagnosticsRouteImport } from './routes/api/consumer/diagnostics'
import { Route as AdminLayoutAdminProdutosRouteImport } from './routes/_adminLayout.admin.produtos'
import { Route as AdminLayoutAdminConfiguracoesRouteImport } from './routes/_adminLayout.admin.configuracoes'
import { Route as AdminLayoutAdminCategoriasRouteImport } from './routes/_adminLayout.admin.categorias'
import { Route as ApiPublicOrdersIdRouteImport } from './routes/api/public/orders.$id'
import { Route as ApiConsumerOrdersDetailsRouteImport } from './routes/api/consumer/orders.details'
import { Route as ApiConsumerOrdersIdRouteImport } from './routes/api/consumer/orders.$id'
import { Route as ApiConsumerOrdersIdStatusRouteImport } from './routes/api/consumer/orders.$id.status'

const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const EntrarRoute = EntrarRouteImport.update({
  id: '/entrar',
  path: '/entrar',
  getParentRoute: () => rootRouteImport,
} as any)
const CuponsRoute = CuponsRouteImport.update({
  id: '/cupons',
  path: '/cupons',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLayoutRoute = AdminLayoutRouteImport.update({
  id: '/_adminLayout',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PedidoIdRoute = PedidoIdRouteImport.update({
  id: '/pedido/$id',
  path: '/pedido/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLayoutAdminIndexRoute = AdminLayoutAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AdminLayoutRoute,
} as any)
const ApiPublicOrdersRoute = ApiPublicOrdersRouteImport.update({
  id: '/api/public/orders',
  path: '/api/public/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiConsumerOrdersRoute = ApiConsumerOrdersRouteImport.update({
  id: '/api/consumer/orders',
  path: '/api/consumer/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiConsumerDiagnosticsRoute = ApiConsumerDiagnosticsRouteImport.update({
  id: '/api/consumer/diagnostics',
  path: '/api/consumer/diagnostics',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLayoutAdminProdutosRoute =
  AdminLayoutAdminProdutosRouteImport.update({
    id: '/admin/produtos',
    path: '/admin/produtos',
    getParentRoute: () => AdminLayoutRoute,
  } as any)
const AdminLayoutAdminConfiguracoesRoute =
  AdminLayoutAdminConfiguracoesRouteImport.update({
    id: '/admin/configuracoes',
    path: '/admin/configuracoes',
    getParentRoute: () => AdminLayoutRoute,
  } as any)
const AdminLayoutAdminCategoriasRoute =
  AdminLayoutAdminCategoriasRouteImport.update({
    id: '/admin/categorias',
    path: '/admin/categorias',
    getParentRoute: () => AdminLayoutRoute,
  } as any)
const ApiPublicOrdersIdRoute = ApiPublicOrdersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiPublicOrdersRoute,
} as any)
const ApiConsumerOrdersDetailsRoute =
  ApiConsumerOrdersDetailsRouteImport.update({
    id: '/details',
    path: '/details',
    getParentRoute: () => ApiConsumerOrdersRoute,
  } as any)
const ApiConsumerOrdersIdRoute = ApiConsumerOrdersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiConsumerOrdersRoute,
} as any)
const ApiConsumerOrdersIdStatusRoute =
  ApiConsumerOrdersIdStatusRouteImport.update({
    id: '/status',
    path: '/status',
    getParentRoute: () => ApiConsumerOrdersIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/checkout': typeof CheckoutRoute
  '/cupons': typeof CuponsRoute
  '/entrar': typeof EntrarRoute
  '/sobre': typeof SobreRoute
  '/admin/login': typeof AdminLoginRoute
  '/pedido/$id': typeof PedidoIdRoute
  '/admin/categorias': typeof AdminLayoutAdminCategoriasRoute
  '/admin/configuracoes': typeof AdminLayoutAdminConfiguracoesRoute
  '/admin/produtos': typeof AdminLayoutAdminProdutosRoute
  '/api/consumer/diagnostics': typeof ApiConsumerDiagnosticsRoute
  '/api/consumer/orders': typeof ApiConsumerOrdersRouteWithChildren
  '/api/public/orders': typeof ApiPublicOrdersRouteWithChildren
  '/admin/': typeof AdminLayoutAdminIndexRoute
  '/api/consumer/orders/$id': typeof ApiConsumerOrdersIdRouteWithChildren
  '/api/consumer/orders/details': typeof ApiConsumerOrdersDetailsRoute
  '/api/public/orders/$id': typeof ApiPublicOrdersIdRoute
  '/api/consumer/orders/$id/status': typeof ApiConsumerOrdersIdStatusRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/checkout': typeof CheckoutRoute
  '/cupons': typeof CuponsRoute
  '/entrar': typeof EntrarRoute
  '/sobre': typeof SobreRoute
  '/admin/login': typeof AdminLoginRoute
  '/pedido/$id': typeof PedidoIdRoute
  '/admin/categorias': typeof AdminLayoutAdminCategoriasRoute
  '/admin/configuracoes': typeof AdminLayoutAdminConfiguracoesRoute
  '/admin/produtos': typeof AdminLayoutAdminProdutosRoute
  '/api/consumer/diagnostics': typeof ApiConsumerDiagnosticsRoute
  '/api/consumer/orders': typeof ApiConsumerOrdersRouteWithChildren
  '/api/public/orders': typeof ApiPublicOrdersRouteWithChildren
  '/admin': typeof AdminLayoutAdminIndexRoute
  '/api/consumer/orders/$id': typeof ApiConsumerOrdersIdRouteWithChildren
  '/api/consumer/orders/details': typeof ApiConsumerOrdersDetailsRoute
  '/api/public/orders/$id': typeof ApiPublicOrdersIdRoute
  '/api/consumer/orders/$id/status': typeof ApiConsumerOrdersIdStatusRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_adminLayout': typeof AdminLayoutRouteWithChildren
  '/checkout': typeof CheckoutRoute
  '/cupons': typeof CuponsRoute
  '/entrar': typeof EntrarRoute
  '/sobre': typeof SobreRoute
  '/admin/login': typeof AdminLoginRoute
  '/pedido/$id': typeof PedidoIdRoute
  '/_adminLayout/admin/categorias': typeof AdminLayoutAdminCategoriasRoute
  '/_adminLayout/admin/configuracoes': typeof AdminLayoutAdminConfiguracoesRoute
  '/_adminLayout/admin/produtos': typeof AdminLayoutAdminProdutosRoute
  '/api/consumer/diagnostics': typeof ApiConsumerDiagnosticsRoute
  '/api/consumer/orders': typeof ApiConsumerOrdersRouteWithChildren
  '/api/public/orders': typeof ApiPublicOrdersRouteWithChildren
  '/_adminLayout/admin/': typeof AdminLayoutAdminIndexRoute
  '/api/consumer/orders/$id': typeof ApiConsumerOrdersIdRouteWithChildren
  '/api/consumer/orders/details': typeof ApiConsumerOrdersDetailsRoute
  '/api/public/orders/$id': typeof ApiPublicOrdersIdRoute
  '/api/consumer/orders/$id/status': typeof ApiConsumerOrdersIdStatusRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/checkout'
    | '/cupons'
    | '/entrar'
    | '/sobre'
    | '/admin/login'
    | '/pedido/$id'
    | '/admin/categorias'
    | '/admin/configuracoes'
    | '/admin/produtos'
    | '/api/consumer/diagnostics'
    | '/api/consumer/orders'
    | '/api/public/orders'
    | '/admin/'
    | '/api/consumer/orders/$id'
    | '/api/consumer/orders/details'
    | '/api/public/orders/$id'
    | '/api/consumer/orders/$id/status'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/checkout'
    | '/cupons'
    | '/entrar'
    | '/sobre'
    | '/admin/login'
    | '/pedido/$id'
    | '/admin/categorias'
    | '/admin/configuracoes'
    | '/admin/produtos'
    | '/api/consumer/diagnostics'
    | '/api/consumer/orders'
    | '/api/public/orders'
    | '/admin'
    | '/api/consumer/orders/$id'
    | '/api/consumer/orders/details'
    | '/api/public/orders/$id'
    | '/api/consumer/orders/$id/status'
  id:
    | '__root__'
    | '/'
    | '/_adminLayout'
    | '/checkout'
    | '/cupons'
    | '/entrar'
    | '/sobre'
    | '/admin/login'
    | '/pedido/$id'
    | '/_adminLayout/admin/categorias'
    | '/_adminLayout/admin/configuracoes'
    | '/_adminLayout/admin/produtos'
    | '/api/consumer/diagnostics'
    | '/api/consumer/orders'
    | '/api/public/orders'
    | '/_adminLayout/admin/'
    | '/api/consumer/orders/$id'
    | '/api/consumer/orders/details'
    | '/api/public/orders/$id'
    | '/api/consumer/orders/$id/status'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminLayoutRoute: typeof AdminLayoutRouteWithChildren
  CheckoutRoute: typeof CheckoutRoute
  CuponsRoute: typeof CuponsRoute
  EntrarRoute: typeof EntrarRoute
  SobreRoute: typeof SobreRoute
  AdminLoginRoute: typeof AdminLoginRoute
  PedidoIdRoute: typeof PedidoIdRoute
  ApiConsumerDiagnosticsRoute: typeof ApiConsumerDiagnosticsRoute
  ApiConsumerOrdersRoute: typeof ApiConsumerOrdersRouteWithChildren
  ApiPublicOrdersRoute: typeof ApiPublicOrdersRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entrar': {
      id: '/entrar'
      path: '/entrar'
      fullPath: '/entrar'
      preLoaderRoute: typeof EntrarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cupons': {
      id: '/cupons'
      path: '/cupons'
      fullPath: '/cupons'
      preLoaderRoute: typeof CuponsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_adminLayout': {
      id: '/_adminLayout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AdminLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pedido/$id': {
      id: '/pedido/$id'
      path: '/pedido/$id'
      fullPath: '/pedido/$id'
      preLoaderRoute: typeof PedidoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_adminLayout/admin/': {
      id: '/_adminLayout/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminLayoutAdminIndexRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/api/public/orders': {
      id: '/api/public/orders'
      path: '/api/public/orders'
      fullPath: '/api/public/orders'
      preLoaderRoute: typeof ApiPublicOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/consumer/orders': {
      id: '/api/consumer/orders'
      path: '/api/consumer/orders'
      fullPath: '/api/consumer/orders'
      preLoaderRoute: typeof ApiConsumerOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/consumer/diagnostics': {
      id: '/api/consumer/diagnostics'
      path: '/api/consumer/diagnostics'
      fullPath: '/api/consumer/diagnostics'
      preLoaderRoute: typeof ApiConsumerDiagnosticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_adminLayout/admin/produtos': {
      id: '/_adminLayout/admin/produtos'
      path: '/admin/produtos'
      fullPath: '/admin/produtos'
      preLoaderRoute: typeof AdminLayoutAdminProdutosRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/_adminLayout/admin/configuracoes': {
      id: '/_adminLayout/admin/configuracoes'
      path: '/admin/configuracoes'
      fullPath: '/admin/configuracoes'
      preLoaderRoute: typeof AdminLayoutAdminConfiguracoesRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/_adminLayout/admin/categorias': {
      id: '/_adminLayout/admin/categorias'
      path: '/admin/categorias'
      fullPath: '/admin/categorias'
      preLoaderRoute: typeof AdminLayoutAdminCategoriasRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/api/public/orders/$id': {
      id: '/api/public/orders/$id'
      path: '/$id'
      fullPath: '/api/public/orders/$id'
      preLoaderRoute: typeof ApiPublicOrdersIdRouteImport
      parentRoute: typeof ApiPublicOrdersRoute
    }
    '/api/consumer/orders/details': {
      id: '/api/consumer/orders/details'
      path: '/details'
      fullPath: '/api/consumer/orders/details'
      preLoaderRoute: typeof ApiConsumerOrdersDetailsRouteImport
      parentRoute: typeof ApiConsumerOrdersRoute
    }
    '/api/consumer/orders/$id': {
      id: '/api/consumer/orders/$id'
      path: '/$id'
      fullPath: '/api/consumer/orders/$id'
      preLoaderRoute: typeof ApiConsumerOrdersIdRouteImport
      parentRoute: typeof ApiConsumerOrdersRoute
    }
    '/api/consumer/orders/$id/status': {
      id: '/api/consumer/orders/$id/status'
      path: '/status'
      fullPath: '/api/consumer/orders/$id/status'
      preLoaderRoute: typeof ApiConsumerOrdersIdStatusRouteImport
      parentRoute: typeof ApiConsumerOrdersIdRoute
    }
  }
}

interface AdminLayoutRouteChildren {
  AdminLayoutAdminCategoriasRoute: typeof AdminLayoutAdminCategoriasRoute
  AdminLayoutAdminConfiguracoesRoute: typeof AdminLayoutAdminConfiguracoesRoute
  AdminLayoutAdminProdutosRoute: typeof AdminLayoutAdminProdutosRoute
  AdminLayoutAdminIndexRoute: typeof AdminLayoutAdminIndexRoute
}

const AdminLayoutRouteChildren: AdminLayoutRouteChildren = {
  AdminLayoutAdminCategoriasRoute: AdminLayoutAdminCategoriasRoute,
  AdminLayoutAdminConfiguracoesRoute: AdminLayoutAdminConfiguracoesRoute,
  AdminLayoutAdminProdutosRoute: AdminLayoutAdminProdutosRoute,
  AdminLayoutAdminIndexRoute: AdminLayoutAdminIndexRoute,
}

const AdminLayoutRouteWithChildren = AdminLayoutRoute._addFileChildren(
  AdminLayoutRouteChildren,
)

interface ApiConsumerOrdersIdRouteChildren {
  ApiConsumerOrdersIdStatusRoute: typeof ApiConsumerOrdersIdStatusRoute
}

const ApiConsumerOrdersIdRouteChildren: ApiConsumerOrdersIdRouteChildren = {
  ApiConsumerOrdersIdStatusRoute: ApiConsumerOrdersIdStatusRoute,
}

const ApiConsumerOrdersIdRouteWithChildren =
  ApiConsumerOrdersIdRoute._addFileChildren(ApiConsumerOrdersIdRouteChildren)

interface ApiConsumerOrdersRouteChildren {
  ApiConsumerOrdersIdRoute: typeof ApiConsumerOrdersIdRouteWithChildren
  ApiConsumerOrdersDetailsRoute: typeof ApiConsumerOrdersDetailsRoute
}

const ApiConsumerOrdersRouteChildren: ApiConsumerOrdersRouteChildren = {
  ApiConsumerOrdersIdRoute: ApiConsumerOrdersIdRouteWithChildren,
  ApiConsumerOrdersDetailsRoute: ApiConsumerOrdersDetailsRoute,
}

const ApiConsumerOrdersRouteWithChildren =
  ApiConsumerOrdersRoute._addFileChildren(ApiConsumerOrdersRouteChildren)

interface ApiPublicOrdersRouteChildren {
  ApiPublicOrdersIdRoute: typeof ApiPublicOrdersIdRoute
}

const ApiPublicOrdersRouteChildren: ApiPublicOrdersRouteChildren = {
  ApiPublicOrdersIdRoute: ApiPublicOrdersIdRoute,
}

const ApiPublicOrdersRouteWithChildren = ApiPublicOrdersRoute._addFileChildren(
  ApiPublicOrdersRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminLayoutRoute: AdminLayoutRouteWithChildren,
  CheckoutRoute: CheckoutRoute,
  CuponsRoute: CuponsRoute,
  EntrarRoute: EntrarRoute,
  SobreRoute: SobreRoute,
  AdminLoginRoute: AdminLoginRoute,
  PedidoIdRoute: PedidoIdRoute,
  ApiConsumerDiagnosticsRoute: ApiConsumerDiagnosticsRoute,
  ApiConsumerOrdersRoute: ApiConsumerOrdersRouteWithChildren,
  ApiPublicOrdersRoute: ApiPublicOrdersRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
